### ISSUE TITLE
Redispatch if webhook URI is not available?

### ISSUE THREAD

**Issue by Guite** [p2-inc/keycloak-events#11]
Hello and thanks for this useful Keycloak extension.

One question for understanding the behavior better: what happens if a POST request could not be sent properly (e.g. because the receiving service is currently being deployed or something)? I saw there is a `SenderException` thrown. Would it be possible to resend the message again?

**Comment by xgp** [comment]
It will retry on a failure from the receiving source. Take a look at the backoff configuration here:
https://github.com/p2-inc/keycloak-events#http-sender

**Comment by Guite** [comment]
Sorry if I oversee something obvious: the `retry` property is `false` by default - can I change this for a webhook which is registered using REST?

**Comment by xgp** [comment]
I see, for webhooks, not just vanilla HTTP sender. Right now, there is no backoff configuration passed when setting up the `WebhookSenderEventListenerProvider`, so it doesn't do it globally (for all webhooks) nor for each one individually. 

You could override the `WebhookSenderEventListenerProviderFactory` and just call the `setConfig` method with the appropriate config vars when you create a new  `WebhookSenderEventListenerProvider`.

I'd also accept a thoughtful default configuration for this as a PR.

**Comment by Guite** [comment]
Thanks, going to take a look during some spare time :smile:

**Comment by xgp** [comment]
Clarification: The default for `retry` is `true` if not specified in the configuration. This line https://github.com/p2-inc/keycloak-events/blob/main/src/main/java/io/phasetwo/keycloak/events/HttpSenderEventListenerProvider.java#L38 evaluates to `false` if nothing is in the config, and the subsequent defaults get used.

Tested in https://github.com/p2-inc/keycloak-events/pull/14
