### ISSUE TITLE
Provide a release jar?

### ISSUE THREAD

**Issue by Guite** [p2-inc/keycloak-events#12]
Would you mind creating a release and providing a binary?
For now I self-compiled a jar, but it would be helpful for project consumers to have a direct download maybe.

**Comment by xgp** [comment]
They're all in Maven central:
https://mvnrepository.com/artifact/io.phasetwo.keycloak
E.g. the most recent `keycloak-events` jar is here:
https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-events/0.10/

**Comment by Guite** [comment]
Nice, thanks for the pointer :+1:
