### ISSUE TITLE
Recommended way to manage webhooks

### ISSUE THREAD

**Issue by MarcinBondaruk** [p2-inc/keycloak-events#16]
Hello,
What would be a recommended way to manage webhooks?
I would love to manage them through git repository somehow. Spinning up a container, waiting till its available and running startup script that performs api calls with curl could be a possibility.
Have you solved encountered such a need in your projects. Please share what would you recommend.
Cheers!

**Comment by xgp** [comment]
Hi @MarcinBondaruk . Thanks for the message. Right now, the only way to manage webhooks is through the API. For our own use, we have a few bash scripts that create some default webhooks when we bootstrap a new Keycloak environment, but nothing that would constitute a "best practice". The old version of Keycloak used to have a facility for running such scripts on startup, but that seems to be absent in the Quarkus version.

**Comment by MarcinBondaruk** [comment]
Thank you very much for your answer! :)
