### ISSUE TITLE
Does not compile for 20.0.3

### ISSUE THREAD

**Issue by ivankovalenko** [p2-inc/keycloak-events#20]
Code is not ready to be used with keycloak 20.0.3

Steps to reproduce
- change property keycloak.version to 20.0.3 in pom.xml
- mvn package
- 
Result
[ERROR] /mnt/src/main/java/io/phasetwo/keycloak/resources/BaseRealmResourceProvider.java:[4,25] package org.keycloak.http does not exist
[ERROR] /mnt/src/main/java/io/phasetwo/keycloak/resources/CorsResource.java:[6,25] package org.keycloak.http does not exist
[ERROR] /mnt/src/main/java/io/phasetwo/keycloak/resources/CorsResource.java:[7,25] package org.keycloak.http does not exist
[ERROR] /mnt/src/main/java/io/phasetwo/keycloak/resources/CorsResource.java:[16,17] cannot find symbol
[ERROR]   symbol:   class HttpRequest
[ERROR]   location: class io.phasetwo.keycloak.resources.CorsResource
[ERROR] /mnt/src/main/java/io/phasetwo/keycloak/resources/CorsResource.java:[18,48] cannot find symbol
[ERROR]   symbol:   class HttpRequest
[ERROR]   location: class io.phasetwo.keycloak.resources.CorsResource

Expected result
 BUILD SUCCESS

**Comment by xgp** [comment]
That's correct. We only keep `main` up to date with the current version of Keycloak. They changed how they do HTTP request/response objects in version `21`, and we had to update to keep current.

**Comment by ivankovalenko** [comment]
I suggest then to remove compability note in README stating the extension is ready for Keycloak >= 15

**Comment by xgp** [comment]
Will do. Thanks.
