### ISSUE TITLE
Missing User object for AdminEvent

### ISSUE THREAD

**Issue by philipsabri** [p2-inc/keycloak-events#48]
The User obejct is missing for the AdminEvents, would be nice to have it to be able to print the username and not only the userid

I created a PR here that would fix it https://github.com/p2-inc/keycloak-events/pull/47

**Comment by xgp** [comment]
@philipsabri Thank you for the PR. I made a few comment there.

**Comment by xgp** [comment]
@philipsabri I haven't had time to investigate what went wrong.

**Comment by philipsabri** [comment]
> @philipsabri I haven't had time to investigate what went wrong.

No worries! The workflow never outputted any errors, perhaps flaky and a rerun could fix it?

**Comment by philipsabri** [comment]
> @philipsabri I haven't had time to investigate what went wrong.

@xgp No worries! The workflow never outputted any errors, perhaps flaky and a rerun could fix it?

**Comment by xgp** [comment]
Looks like that was it. I ran it again and it worked. Thanks again.
