### ISSUE TITLE
Unable to Get Webhooks/Attributes API endpoint working

### ISSUE THREAD

**Issue by manju754** [p2-inc/keycloak-events#49]
HI,

I bought up the keycloak using the command

`docker run -d --name phasetwo_test-keycloak -p 9000:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE_PATH=/auth -e KC_LOG_LEVEL=debug quay.io/phasetwo/phasetwo-keycloak:latest start-dev`

I enabled the webhook listener from the Admin UI

![image](https://github.com/p2-inc/keycloak-events/assets/2039216/67dc5f10-0e60-4730-be39-62b5341b09df)

However, When I try to hit any webhooks /attributes endpoint I get 404 not found

![image](https://github.com/p2-inc/keycloak-events/assets/2039216/5132b0ed-e99b-4d6a-b99f-d3cf66b340fc)

![image](https://github.com/p2-inc/keycloak-events/assets/2039216/3e2a663e-a610-45a9-b4c7-0f8dbf18f8c9)

Do we have extra configurations to be done to make these endpoints work?

What am I missing here?

Appreciate your help

**Comment by xgp** [comment]
Try without the “/admin” in the path. E.g. “/auth/realms/test/webhooks”.
