### ISSUE TITLE
Same event sent from different realms

### ISSUE THREAD

**Issue by feg624** [p2-inc/keycloak-events#59]
Hi, I'm using the HTTP Sender event with success, but in the scenario where I have the following realms structure

Master Realm --> no events configuration (default)
- Realm 1 --> attributes points to listener 1
- Realm 2 --> attributes points to listener 2

when a change is made on either Realm 1 or Realm 2, the event is sent to both listeners.

Thanks in advance.

Franco

**Comment by xgp** [comment]
What version are you using? This was fixed in https://github.com/p2-inc/keycloak-events/commit/76852a7375f81ae8b2b8e96bc37971139044b062

**Comment by feg624** [comment]
Hi @xgp , thanks for pointing this out. I'm using version 23.0.4. On which version may I find this fix implemented?

Regards,

Franco

**Comment by feg624** [comment]
Closing per the previous comments.
