### ISSUE TITLE
QUESTION | Is there any documentation on the data models that are sent with configured webhooks?

### ISSUE THREAD

**Issue by alainkaiser** [p2-inc/keycloak-events#62]
After some research, I could successfully setup a Webhook (currently for all possible events) and test the Webhook via pipedream. Works great!

The plan now is that I will address a custom web API (written in .NET) via webhook. What I am currently asking myself: Can I find documentation somewhere on the data models that are sent for the various events?

Thanks in advance for an answer!

**Comment by xgp** [comment]
There is some documentation here: https://phasetwo.io/docs/audit-logs/api/#field-definitions

Also, the object (`ExtendedAdminEvent`) that gets serialized (by jackson) is defined here:

- https://github.com/p2-inc/keycloak-events/blob/main/src/main/java/io/phasetwo/keycloak/representation/ExtendedAdminEvent.java
- which extends this: https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/events/admin/AdminEvent.java
- and includes this: https://github.com/p2-inc/keycloak-events/blob/main/src/main/java/io/phasetwo/keycloak/representation/ExtendedAuthDetails.java

If you're not familiar with jackson, it just takes an object and calls all the get methods, unless the method is annotated with `JsonIgnore`. It generates the key name with the part after the `get`, unless the method is annotated with `JsonProperty`.

**Comment by alainkaiser** [comment]
@xgp Thank you very much, I really appreciate your answers and will read up on them.
