### ISSUE TITLE
Organization related events

### ISSUE THREAD

**Issue by Degoya-Studio** [p2-inc/keycloak-events#65]
Hi, are you planning on adding organization related events, such as the creation of an organization or adding of users to one? https://www.keycloak.org/2024/06/announcement-keycloak-organizations

**Comment by xgp** [comment]
You're in the wrong place. That's link is for the native Keycloak organization feature. For inquiries about their functionality, please use their repository https://github.com/keycloak/keycloak

The extension they copied it from is here https://github.com/p2-inc/keycloak-orgs and has already implemented several event types https://github.com/p2-inc/keycloak-orgs/blob/main/docs/events.md
