### ISSUE TITLE
for group and client role event-listener cant use delete operations 

### ISSUE THREAD

**Issue by mtalhamrl** [p2-inc/keycloak-events#69]
for user i can use admin.USER-CREATE  admin.USER-UPDATE  admin.USER-DELETE 
for client role i can use admin.CLIENT_ROLE-CREATE , admin.CLIENT_ROLE-UPDATE
for groups i can use admin.GROUP-CREATE , admin.GROUP-UPDATE but i cant use delete operations for client role and group .

**Comment by xgp** [comment]
This is a question for Keycloak and has nothing to do with this extension. Please use https://github.com/keycloak/keycloak/issues
