### ISSUE TITLE
Simple tutorial to start p2-inc/keycloak-events with http sender

### ISSUE THREAD

**Issue by adrian-moisa** [p2-inc/keycloak-events#70]
I'm trying to use the official phasetwo keycloak docker image. Sadly the main readme is really terse and hard to figure out. Also could not find any tutorial online. Tried to look trough all the issues of the repo to find code samples.

What I understand so far:

Start p2 KC:
```sh
docker run -dt --name sys-auth-events \
-p 8081:8080 \
-e KEYCLOAK_ADMIN=admin \
-e KEYCLOAK_ADMIN_PASSWORD=“1234” \
-e KC_DB=postgres \
-e KC_DB_URL_HOST=host.docker.internal \
-e KC_DB_URL_PORT=5432 \
-e KC_DB_URL_DATABASE=keycloak \
-e KC_DB_USERNAME=postgres \
-e KC_DB_PASSWORD="1234" \
-e KC_HEALTH_ENABLED=true \
-e KC_METRICS_ENABLED=true \
-e QUARKUS_HTTP_ACCESS_LOG_ENABLED=true \
quay.io/phasetwo/phasetwo-keycloak:latest start-dev
```

- Using the docker image means I no longer have to run the kc maven build. I found in `opt/keycloak/providers`

<img width="517" alt="image" src="https://github.com/user-attachments/assets/f181936f-dd13-4d41-bc26-602864c1c079">

I saw the readme there. However I assume since I'm not changing anything except config there's no need for me to upload custom jars.

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/05f70657-cbaa-4f7a-a47b-17cb5625e86d">

I understand that the next step would be to create a new realm and provide the following json as config.

```json
{
  "id": "demo",
  "realm": "demo",
  "attributes": {
    "_providerConfig.ext-event-http": "{\"targetUri\": \"https://demo.api/endpoint-to-be-called-by-kc\"}"
  }
}
```

Also in realm settings / events / i need to enable `ext-event-http`

<img width="635" alt="image" src="https://github.com/user-attachments/assets/182c021d-5e23-4cfb-8077-9cbe30cfbc4b">

I also saw in one of the repo issues mention about this URLs: (note I've installed KC at 8081 and at root level, I don't need `-e KC_HTTP_RELATIVE_PATH=/auth`)
```
http://localhost:8081/realms/demo/events
http://localhost:8081/realms/demo/attributes
```
Not sure what these do. Or if I need them for http sender. So far this is what I see when visiting them.  Which is not the same as "not found"

<img width="645" alt="image" src="https://github.com/user-attachments/assets/b0d5ef50-2a75-4d3e-aabf-c4baee867314">

I'm not interested in webhooks. Though probably for people interested in webhooks a beginner level tutorial would make much difference. 

Given all the above, am I missing smth out? Any help will be appreciated. Thank you!

**Comment by xgp** [comment]
@adrian-moisa You've figured most of it out. You just need to store your configuration as a Realm attribute. This can be done using the Keycloak API to get the realm, and then [put an update](https://www.keycloak.org/docs-api/latest/rest-api/index.html#_put_adminrealmsrealm) that includes your new attribute as part of the array. The "key" for that attribute is `_providerConfig.ext-event-http` and the value is the configuration object, e.g. `{"targetUri":"https://demo.api/endpoint-to-be-called-by-kc"}`

Keycloak doesn't make it easy to CRUD individual attributes, so the endpoint you found (`http://localhost:8081/realms/demo/attributes`) is a convenience we built for managing individual attributes. More documentation is here https://phasetwo.io/api/category/attributes/

**Comment by adrian-moisa** [comment]
Thanks @xgp  for the quick answer! Looks like KC folks had a discussion about adding an admin GUI for realm attributes. Too bad nothing was released yet. https://github.com/keycloak/keycloak/discussions/23678 . I'll see what I can achieve this evening and update you if anything clicks.

**Comment by adrian-moisa** [comment]
Will renaming a test account in admin trigger an event that will be relayed by the http sender?

**Comment by adrian-moisa** [comment]
Following advice from here https://github.com/p2-inc/keycloak-events/issues/5 I was able to get the access token and run the attributes GET endpoint. However the events is a POST and I have no idea what to use for body. Still not able to see any calls from KC to my users api.

**Comment by adrian-moisa** [comment]
There we go! Party time! 🎉🥳

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/57732214-7cc2-48a8-be15-daa3ea76d589">

Damn that took some wrestling to get it done :D

**Comment by xgp** [comment]
Thank you for your persistence! If you have the time to write up the steps you took, I’d be pleased to put it in the README. 

Also, if you are using the Phase Two docker image, and have turned on the phasetwo.v2 admin theme, there is an “Attributes” tab in the “Realm Settings” that you can use to view and set Realm attributes.

**Comment by adrian-moisa** [comment]
I tried enabling it, but I don't see this `Attributes` tab. I even tried restarting the container in docker to make sure the theme is selected. Maybe I'm doing smth wrong.

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/e01f2a4c-b5b4-4f03-81e3-4066edbc2dfa">

I'll try to find some time to cleanup the findings and improve the readme with a PR. Running a bit heavy now, but I'm willing to help as soon as I get some spare time.

**Comment by xgp** [comment]
You have to log out and log back in. Also, if you are logging into `master` and then switching to another realm, you need to set it as the "Admin theme" for `master`.

**Comment by adrian-moisa** [comment]
Indeed it works, I see the tab. Thanks for the hint! Though I have some reservation over the idea of overriding all realms at once. I use a separate realm from master for my app. And potentially will have more realms later. I'd prefer to customise one by one.

**Comment by xgp** [comment]
> overriding all realms at once

What I suggested doesn't override all realms. This is how themeing works in Keycloak. It activates the admin theme **for the realm user you are logged in as**. If you create an account with admin roles in your target realm and log in to that console (e.g. `https://myauth.com/auth/admin/some-other-realm/console/`, it will use whatever admin theme you have set up for that realm.

IMHO, it is a bad practice to use the `master` for **anything** other than creating new realms and admin accounts. Using the `master` realm is a big security problem, and it leads to lots of confusion like this.

**Comment by adrian-moisa** [comment]
Oh I see, it makes sense!

**Comment by xgp** [comment]
They are similar. Webhooks gives you the ability to filter by type of event, and there is an API to create webhooks. You can give a user or service account the `view-events` and `manage-events` roles, which will give them the ability to create webhooks, where a user must have `manage-realm` role to set Realm Attributes. 

> All I can say as a diff is that webhooks are more flexible as they allow multiple systems to receive events without changing the sender's configuration.

Yes!

**Comment by adrian-moisa** [comment]
Was wondering, is there a way to subscribe the http sender only to certain types of events? For example right now I want only the type: REGISTER. I see token introspection as well and that one could flood my target endpoint. Thanks for the support so far!

**Comment by xgp** [comment]
Webhooks allow filtering by type, but the standard HTTP sender does not.
