### ISSUE TITLE
Access Register event not triggered when manually sending a Magic Link via our own Backend

### ISSUE THREAD

**Issue by alainkaiser** [p2-inc/keycloak-events#83]
Hey :)

We are successfully using your magic-link extension for keycloak in our solution. We trigger the sending of the magic link email via our own backend endpoint. This endpoint communicates with the keycloak admin api. We pretty much followed the discussion here to come up with a working solution: https://github.com/p2-inc/keycloak-magic-link/issues/82.

Now - We also use the keycloak-events plugin and the included webhooks to sync data from keycloak to our application database. We have several events in place for which we offer an endpoint on our backend:

- access.REGISTER
- admin.REALM_ROLE_MAPPING-DELETE
- admin.USER-CREATE
- admin.USER-UPDATE
- admin.REALM_ROLE_MAPPING-CREATE
- admin.USER-DELETE

Now when we trigger the Magic Link via Keycloak directly (Login Template), the `access.REGISTER` event is fired and we consume it via our endpoint. But if we trigger the sending of the magic link via our own backend, nothing happens, the `access.REGISTER` is not triggered at all.

Is there another similar event type I can use or is this simply not supported yet? What could be a possible workaround?

Thanks in advance for your help!

**Comment by alainkaiser** [comment]
So I invested some more minutes and found the reason why I am not getting the event. There is a small difference in the webhook payload.

Payload for the `access.REGISTER` if the Magic Link triggered via Keycloak Template (Browser Flow):
{
  "time": 1732704905059,
  "realmId": "TEST",
  "uid": "TEST",
  "authDetails": {
    "realmId": "TEST",
    "userId": "TEST",
    "ipAddress": "TEST,
    "username": "TEST",
    "sessionId": "TEST"
  },
  "details": {
    "register_method": "magic",
    "email": "TEST",
    "username": "TEST"
  },
  "type": "access.REGISTER"
}

Payload for the `access.REGISTER` if the Magic Link triggered via our own Backend / Keycloak Admin API:
{
  "time": 1732705384177,
  "realmId": "TEST",
  "uid": "TEST",
  "authDetails": {
    "realmId": "TEST",
    "userId": "TEST",
    "ipAddress": "TEST",
    "username": "TEST"
  },
  "details": {
    "register_method": "TEST",
    "email": "TEST",
    "username": "TEST"
  },
  "type": "access.REGISTER"
}

As you can see, inside the `authDetails` object, the property `sessionId` is missing when triggered via Admin API. Not sure why...? This was the reason why the request could not be parsed on our own backend (we expeceted `sessionId` to be present).

**Comment by xgp** [comment]
@alainkaiser Thanks for the report. Can you please detail the call you are making when you say "if we trigger the sending of the magic link via our own backend"? 

If you are calling the [REST resource to create a magic link](https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/java/io/phasetwo/keycloak/magic/resources/MagicLinkResource.java#L30), then it should be firing a register event [here](https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/java/io/phasetwo/keycloak/magic/resources/MagicLinkResource.java#L53-L61) when the user needs to be created. This is the same method that gets invoked in the [authenticator](https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/java/io/phasetwo/keycloak/magic/auth/MagicLinkAuthenticator.java#L74-L82).

**Comment by xgp** [comment]
> As you can see, inside the authDetails object, the property sessionId is missing when triggered via Admin API. Not sure why...? This was the reason why the request could not be parsed on our own backend (we expeceted sessionId to be present).

`sessionId` indicates an authentication session ID. When you are calling it from an authenticator, there is a sessionId, but when you are calling it from a REST resource, there is no authentication session. Note: a user session is different from an authentication session. The latter only occurs during an authentication, whereas the former occurs after a successful authentication.

**Comment by alainkaiser** [comment]
@xgp Thanks for your quick response, appreciate it very much! I managed to solve it - the event is triggered (please see my second comment). But the payload is slightly different.
