### ISSUE TITLE
Webhooks permanently broken when connection is cut off

### ISSUE THREAD

**Issue by Skyppid** [p2-inc/keycloak-events#9]
Scenario: We're hooking User and GroupMembership events in our ASP.NET Core backend application so we can conveniently access some of the user's information.

Setup: ASP app running on localhost (Windows), Keycloak running in a docker container, plugin hook is configured for the docker host, app listens on 0.0.0.0/users/hook and retrieves events usually.

Now when adding a user to multiple groups the hooks fire fast and database interaction runs into concurrency issues. Fixed that with isolated transactions which resulted in failures. For some reason when I stop the application now to fix stuff and retry, the hooks don't fire anymore.

In my Keycloak's logs I can find the following errors popping up all the time:

> 2022-12-13 13:12:59 2022-12-13 12:12:59,022 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-4) retrying in 394 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:13:14 2022-12-13 12:13:14,381 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-1) retrying in 460 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:13:14 2022-12-13 12:13:14,381 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-2) retrying in 702 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:15:12 2022-12-13 12:15:12,141 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-6) retrying in 681 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:15:27 2022-12-13 12:15:27,501 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-5) retrying in 753 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:15:27 2022-12-13 12:15:27,501 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-3) retrying in 462 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:17:25 2022-12-13 12:17:25,261 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-7) retrying in 1262 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:17:40 2022-12-13 12:17:40,621 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-4) retrying in 861 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-13 13:17:40 2022-12-13 12:17:40,621 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-8) retrying in 1125 due to java.net.ConnectException: Connection timed out (Connection timed out)

When I shut down the container and reboot it, the state remains. Hooks don't work anymore until I completely recreate the container. The following exception occurs when shutting down the Keycloak container:

> 2022-12-13 13:19:59 2022-12-13 12:19:59,691 WARN  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-10) Uncaught Sender error: java.lang.IllegalStateException: Connection pool shut down
> 2022-12-13 13:19:59     at org.apache.http.util.Asserts.check(Asserts.java:34)
> 2022-12-13 13:19:59     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:278)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:217)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.send(HttpSenderEventListenerProvider.java:76)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.WebhookSenderEventListenerProvider.send(WebhookSenderEventListenerProvider.java:142)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.SenderEventListenerProvider.lambda$schedule$0(SenderEventListenerProvider.java:109)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 2022-12-13 13:19:59     at java.base/java.lang.Thread.run(Thread.java:829)
> 2022-12-13 13:19:59 
> 2022-12-13 13:19:59 2022-12-13 12:19:59,691 WARN  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-4) Uncaught Sender error: java.lang.IllegalStateException: Connection pool shut down
> 2022-12-13 13:19:59     at org.apache.http.util.Asserts.check(Asserts.java:34)
> 2022-12-13 13:19:59     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:278)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:217)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.send(HttpSenderEventListenerProvider.java:76)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.WebhookSenderEventListenerProvider.send(WebhookSenderEventListenerProvider.java:142)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.SenderEventListenerProvider.lambda$schedule$0(SenderEventListenerProvider.java:109)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 2022-12-13 13:19:59     at java.base/java.lang.Thread.run(Thread.java:829)
> 2022-12-13 13:19:59 
> 2022-12-13 13:19:59 2022-12-13 12:19:59,691 WARN  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-6) Uncaught Sender error: java.lang.IllegalStateException: Connection pool shut down
> 2022-12-13 13:19:59     at org.apache.http.util.Asserts.check(Asserts.java:34)
> 2022-12-13 13:19:59     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 2022-12-13 13:19:59     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 2022-12-13 13:19:59     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:278)
> 2022-12-13 13:19:59     at org.keycloak.broker.provider.util.SimpleHttp.asResponse(SimpleHttp.java:217)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.HttpSenderEventListenerProvider.send(HttpSenderEventListenerProvider.java:76)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.WebhookSenderEventListenerProvider.send(WebhookSenderEventListenerProvider.java:142)
> 2022-12-13 13:19:59     at io.phasetwo.keycloak.events.SenderEventListenerProvider.lambda$schedule$0(SenderEventListenerProvider.java:109)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 2022-12-13 13:19:59     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 2022-12-13 13:19:59     at java.base/java.lang.Thread.run(Thread.java:829)
> 2022-12-13 13:19:59 
> 2022-12-13 13:19:59 2022-12-13 12:19:59,807 INFO  [io.phasetwo.keycloak.events.HttpSenderEventListenerProviderFactory] (main) Shutting down scheduler
> 2022-12-13 13:19:59 2022-12-13 12:19:59,807 INFO  [io.phasetwo.keycloak.events.WebhookSenderEventListenerProviderFactory] (main) Shutting down scheduler
> 2022-12-13 13:19:59 2022-12-13 12:19:59,827 INFO  [io.quarkus] (main) Keycloak stopped in 0.152s

Any help and a potential fix would be appreciated :)

**Comment by xgp** [comment]
None of this is unexpected. The first `java.net.ConnectException: Connection timed out` errors are because your server isn't responding within the timeout, and the webhook sender is rescheduling the event. The second `java.lang.IllegalStateException: Connection pool shut down` errors are because Keycloak is shutting down various services, and shuts down the HTTP connection pool before it shuts down the scheduler in the webhook sender.

The "fix" is to make your event handling server respond quickly. Tweaking the exponential backoff variables might get you some relieve when there are bursts, but the expectation is that webhooks are sent to a server that will respond immediately.

**Comment by Skyppid** [comment]
Well that might have been the wrong logs then. But I am quite certain there's something wrong. Just now I have the same issue. I tested for some time quite well and now I just don't receive any hooks anymore. The app is running as usual and the logs get flooded with connection timeouts. 

Any chance there is an issue where cut off connections aren't cleaned up and it retires to send over these? I don't know when this happens exactly but since I sometimes just killed the app in Visual Studio when I had to fix an issue after stepping through, it might ends in randomly breaking the event sender.

The time it worked I received different retry messages as you can see here. Once it started to fail sending hooks it's what you see starting from 12:46 going on:

> 2022-12-20 13:25:48 keycloak-dev         | 
> 2022-12-20 13:26:20 keycloak-dev         | 2022-12-20 12:26:20,265 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-11) retrying in 496 due to null
> 2022-12-20 13:26:25 keycloak-dev         | 2022-12-20 12:26:25,769 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-11) retrying in 876 due to null
> 2022-12-20 13:30:51 keycloak-dev         | 2022-12-20 12:30:51,339 WARN  [org.keycloak.protocol.oidc.utils.AcrUtils] (executor-thread-63) Invalid realm configuration (ACR-LOA map)
> 2022-12-20 13:30:51 keycloak-dev         | 2022-12-20 12:30:51,449 WARN  [org.keycloak.protocol.oidc.utils.AcrUtils] (executor-thread-63) Invalid realm configuration (ACR-LOA map)
> 2022-12-20 13:33:01 keycloak-dev         | 2022-12-20 12:33:01,173 WARN  [org.keycloak.protocol.oidc.utils.AcrUtils] (executor-thread-78) Invalid realm configuration (ACR-LOA map)
> 2022-12-20 13:33:01 keycloak-dev         | 2022-12-20 12:33:01,175 WARN  [org.keycloak.protocol.oidc.utils.AcrUtils] (executor-thread-78) Invalid realm configuration (ACR-LOA map)
> 2022-12-20 13:46:42 keycloak-dev         | 2022-12-20 12:46:42,877 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-14) retrying in 571 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-20 13:46:42 keycloak-dev         | 2022-12-20 12:46:42,877 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-11) retrying in 256 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-20 13:46:42 keycloak-dev         | 2022-12-20 12:46:42,877 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-9) retrying in 577 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-20 13:46:42 keycloak-dev         | 2022-12-20 12:46:42,877 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-5) retrying in 528 due to java.net.ConnectException: Connection timed out (Connection timed out)
> 2022-12-20 13:46:42 keycloak-dev         | 2022-12-20 12:46:42,877 INFO  [io.phasetwo.keycloak.events.SenderEventListenerProvider] (pool-5-thread-10) retrying in 468 due to java.net.ConnectException: Connection timed out (Connection timed out)
